spring.application.name=commerce-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecombackend
spring.datasource.username=root
spring.datasource.password=piyushp@rdhi999
spring.jpa.hibernate.ddl-auto=update

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=604800000

logging.level.org.springframework.security=DEBUG